# Generated by Django 5.2.4 on 2025-08-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0002_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
