# Generated by Django 5.2.4 on 2025-08-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0003_alter_produtos_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
